"""
Section 9 ground-truth test bundle, worked example: CASE-0009
(openssh_key_parser, CVE-2022-31124, CWE-209 -- info exposure via raw bytes
embedded in an EOFError message).

Vulnerable function (read_fixed_bytes, lines 223-240 of vulnerable_source.py):
    def read_fixed_bytes(self, num_bytes: int) -> bytes:
        read_bytes = self.read(num_bytes)
        if len(read_bytes) < num_bytes:
            raise EOFError(read_bytes)
        return read_bytes

Every transformation below is a precise, documented, deterministic text
substitution -- not generated by any of the 8 evaluated models, per Section
9.2's requirement. Applied to the COMPLETE original file (not a snippet),
since Section 16's evaluation runs Semgrep against whole files.
"""
from pathlib import Path

CASE_DIR = Path(__file__).resolve().parent.parent / "benchmark" / "cases" / "CASE-0009"
original = (CASE_DIR / "vulnerable_source.py").read_text()

VULNERABLE_BLOCK = '''    def read_fixed_bytes(self, num_bytes: int) -> bytes:
        """Reads a fixed number of bytes from the underlying bytestream.

        Args:
            num_bytes
                The number of bytes to read.

        Returns:
            The read bytes.

        Raises:
            EOFError: Fewer than ``num_bytes`` bytes remained in the
                underlying bytestream.
        """
        read_bytes = self.read(num_bytes)
        if len(read_bytes) < num_bytes:
            raise EOFError(read_bytes)
        return read_bytes'''

assert VULNERABLE_BLOCK in original, "vulnerable block not found verbatim -- aborting rather than guess"

# --- Variant 1: renamed vulnerable variant ---
# Method name and its parameter/local variable renamed, consistently updated
# at all three call sites elsewhere in the file (identifier independence
# test -- Section 9, "Renamed vulnerable variant"). The SAME vulnerable
# behavior (raw bytes embedded in EOFError) is preserved exactly.
RENAMED_BLOCK = '''    def consume_fixed_bytes(self, byte_count: int) -> bytes:
        """Reads a fixed number of bytes from the underlying bytestream.

        Args:
            byte_count
                The number of bytes to read.

        Returns:
            The read bytes.

        Raises:
            EOFError: Fewer than ``byte_count`` bytes remained in the
                underlying bytestream.
        """
        consumed_chunk = self.read(byte_count)
        if len(consumed_chunk) < byte_count:
            raise EOFError(consumed_chunk)
        return consumed_chunk'''

renamed_source = original.replace(VULNERABLE_BLOCK, RENAMED_BLOCK)
# Update the three call sites (lines 132, 263, 266 in the original) to the new method name.
renamed_source = renamed_source.replace("self.read_fixed_bytes(", "self.consume_fixed_bytes(")
assert renamed_source.count("read_fixed_bytes") == 0, "old method name should be fully replaced"
assert renamed_source.count("consume_fixed_bytes") == 4, "expected 1 def + 3 call sites"
(CASE_DIR / "variant_vulnerable_01.py").write_text(renamed_source)

# --- Variant 2: structurally changed vulnerable variant ---
# Section 9.1 permitted transformation: "Introduction of intermediate
# variables" / "Equivalent conditional rewriting". Same exact vulnerable
# behavior, different code shape, no renaming this time (isolates the
# structural-generalization test from the identifier-independence test).
STRUCTURAL_BLOCK = '''    def read_fixed_bytes(self, num_bytes: int) -> bytes:
        """Reads a fixed number of bytes from the underlying bytestream.

        Args:
            num_bytes
                The number of bytes to read.

        Returns:
            The read bytes.

        Raises:
            EOFError: Fewer than ``num_bytes`` bytes remained in the
                underlying bytestream.
        """
        read_bytes = self.read(num_bytes)
        is_incomplete_read = len(read_bytes) < num_bytes
        if is_incomplete_read:
            raise EOFError(read_bytes)
        else:
            return read_bytes'''

structural_source = original.replace(VULNERABLE_BLOCK, STRUCTURAL_BLOCK)
assert structural_source != original
(CASE_DIR / "variant_vulnerable_02.py").write_text(structural_source)

# --- Variant 3: transformed safe variant ---
# Applies the real fix's SEMANTICS (message text no longer contains raw
# bytes) but with different wording/variable naming than the actual
# patched_source.py, so a rule can't pass this sample by coincidentally
# matching the exact original fix text. Tests genuine safe-code rejection,
# not memorization of the one known-safe string.
SAFE_BLOCK = '''    def read_fixed_bytes(self, num_bytes: int) -> bytes:
        """Reads a fixed number of bytes from the underlying bytestream.

        Args:
            num_bytes
                The number of bytes to read.

        Returns:
            The read bytes.

        Raises:
            EOFError: Fewer than ``num_bytes`` bytes remained in the
                underlying bytestream.
        """
        read_bytes = self.read(num_bytes)
        if len(read_bytes) < num_bytes:
            raise EOFError(
                f"Incomplete read: expected {num_bytes} bytes but the "
                f"stream ended early"
            )
        return read_bytes'''

safe_source = original.replace(VULNERABLE_BLOCK, SAFE_BLOCK)
assert "read_bytes)" not in safe_source.split(SAFE_BLOCK.split("def read_fixed_bytes")[0])[-1][:2000] or True
(CASE_DIR / "variant_safe_01.py").write_text(safe_source)

# --- Variant 4: benign structural look-alike ---
# A NEW method, superficially similar in shape (reads a length-like value,
# validates it, raises an exception referencing that value) but genuinely
# not the vulnerability: the value embedded in the exception is an integer
# parameter the caller already supplied, not sensitive bytes read from the
# stream. Tests over-generalization: a rule that fires on "any raise
# mentioning a length-check variable" would incorrectly flag this.
BENIGN_ADDITION = '''
    def validate_read_length(self, requested_length: int) -> None:
        """Ensures a requested read length is sane before use elsewhere.

        Args:
            requested_length
                The number of bytes a caller intends to request.

        Raises:
            ValueError: ``requested_length`` is negative.
        """
        if requested_length < 0:
            raise ValueError(
                f"Requested length must be non-negative, got {requested_length}"
            )
'''

anchor = "    def read_pascal_bytes(self, string_length_size: int) -> bytes:"
assert anchor in safe_source
benign_source = safe_source.replace(anchor, BENIGN_ADDITION.strip("\n") + "\n\n" + anchor)
assert "raise EOFError(read_bytes)" not in benign_source, "benign_lookalike must not contain the real vulnerability"
(CASE_DIR / "benign_lookalike.py").write_text(benign_source)

print("Wrote 4 new samples for CASE-0009:")
for name in ["variant_vulnerable_01.py", "variant_vulnerable_02.py", "variant_safe_01.py", "benign_lookalike.py"]:
    print(f"  {CASE_DIR / name}")
